# 配置数据源相关的属性
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_db
      username: root
      password: root
      type: com.mchange.v2.c3p0.ComboPooledDataSource


# 配置MyBatis相关的属性
mybatis:
    typeAliasesPackage: cn.itcast.springboot.domain
    configLocation: classpath:mybatis-config.xml
    mapperLocations: classpath:mappers/**/*Mapper.xml