# 配置数据源相关的属性
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_db
      username: root
      password: root
      type: com.mchange.v2.c3p0.ComboPooledDataSource